### ISSUE TITLE
Navbar is not responsive.

### ISSUE THREAD

**Issue by Ankitchaudharyy** [casbin/casbin-website-v2#131] opened 2022-12-26 17:58 UTC
Navbar Items overlap each other when the width of the screen is reduced.

- Screenshot attached
<img width="1052" alt="Screenshot 2022-12-26 at 11 24 10 PM" src="https://user-images.githubusercontent.com/46367738/209573506-13ca7579-eeac-48c9-be55-dff1d7062e32.png">

**Comment by Ankitchaudharyy** [comment] 2022-12-26 17:58
I can work on this issue. Please assign it to me.

**Comment by Rew0611** [comment] 2022-12-27 09:27
I want to work on this issue

**Comment by anurag0006** [comment] 2023-01-02 15:41
Hii @hsluoyz, As the issue is still open i wanna work on this issue...Can You please assign this to me?

**Comment by MahendraBishnoi29** [comment] 2023-01-04 10:23
@hsluoyz is it still open? if yes then i want to work on it

**Comment by mohd-asad** [comment] 2023-01-13 16:06
Hi, I can fix this bug, plz assign it me.

**Comment by mohd-asad** [comment] 2023-01-13 16:09
On the navbar, titles are shifted downward. I can set them in the middle.

**Closed** 2023-01-13 16:11 UTC
Labels: bug
